### ISSUE TITLE
this is not a legal doc

### ISSUE THREAD

**Issue by johndickinson** [Sinodun/draft-dprive-bcp-op#14]
from minutes and listening to proceedings of IETF102:

DKG: We are not writing a legal doc. We should expect to change and update the
document in time as BCPs change.

**Comment by saradickinson** [comment]
Version -02 says this:
"Community insight [or judgment?] about operational practices can
   change quickly, and experience shows that a Best Current Practice
   (BCP) document about privacy and security is a point-in-time
   statement.  Readers are advised to seek out any errata or updates
   that apply to this document."
