### ISSUE TITLE
draft-ietf-tls-dnssec-chain-extension-07 is expired

### ISSUE THREAD

**Issue by johndickinson** [Sinodun/draft-dprive-bcp-op#17]
We reference this draft

**Comment by saradickinson** [comment]
As announced on the TLS mailing list 9th Nov by Sean Turner:

"At IETF103, the WG considered the way forward for draft-ietf-tls-dnssec-chain-extension.  Based on the attempts at discussion on the list and the sense in the room, the chairs believe that there is no longer interest in continuing work on draft-ietf-tls-dnssec-chain-extension as a WG document.  The chairs will be dropping it as a WG item soon. 

To be clear, work on delivering DNSSEC records via a TLS extension can continue.  The authors and/or others are free to progress this draft through other avenues or not to obtain IANA code points (see [0]). "

**Comment by johndickinson** [comment]
I am going to remove this reference and associated text.
