### ISSUE TITLE
DANE

### ISSUE THREAD

**Issue by johndickinson** [Sinodun/draft-dprive-bcp-op#18]
DANE is in both the mitigations and optimisation for authentication. this an issue 17 mean there is no longer any Optimizations for Authentication

**Comment by saradickinson** [comment]
The mitigation section is describing DANE in general, the optimisation section is describing using the specific TLSA options that do not require a PKIX cert (i.e. key based DANE) which is actually described in the Security considerations:
https://tools.ietf.org/html/rfc8310#page-19
"DNS clients SHOULD implement (1) support for the mechanisms described
   in Section 8.2 and (2) offering a configuration option that limits
   authentication to using only those mechanisms (i.e., with no fallback
   to pure PKIX-based authentication) such that authenticating solely
   via the PKIX infrastructure can be avoided."

I think we can clarify this with better text.

**Comment by saradickinson** [comment]
In version -02 DANE was moved to be optimisation only.
